# center
# 現在のwindow
set-window-option -g window-status-current-format "\
#[bg=colour25, fg=colour7] #I #W \
"
# 他のwindow
set-window-option -g window-status-format "\
#[bg=colour238,fg=colour7] #I #W \
"

set -g status-fg colour7 # ステータスバーの文字色
set -g status-bg colour240 # ステータスバーの背景色
