# https://github.com/Shougo/dein.vim/blob/master/doc/dein.txt
# depends を指定するときは名前のみ指定する
# depends に指定しただけではインストールまではされず、別途 [[plugins]] で指定する必要がある

# 環境
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]] # :DenopsHello => Hello
repo = 'vim-denops/denops-helloworld.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# color

[[plugins]]
repo = 'cocopon/iceberg.vim'
# highlightの設定は https://github.com/cocopon/iceberg.vim/issues/101 がcloseするまで
lua_add = '''
  vim.cmd('colorscheme iceberg')
  vim.cmd('highlight FloatBorder guibg=#242940 guifg=#242940 ctermbg=none')
'''

# fuzzy finder

[[plugins]]
repo = 'nvim-telescope/telescope-fzy-native.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['nvim-lua/plenary.nvim', 'nvim-telescope/telescope-fzf-native.nvim']
lua_add = '''
  -- live_grep は ripgrep に依存している
  vim.api.nvim_set_keymap('n', '<Space>f', ':lua require("telescope.builtin").find_files()<cr>', { noremap = true })
  vim.api.nvim_set_keymap('n', '<Space>g', ':lua require("telescope.builtin").live_grep()<cr>',  { noremap = true })
  vim.api.nvim_set_keymap('n', '<Space>b', ':lua require("telescope.builtin").buffers()<cr>',    { noremap = true })
  vim.api.nvim_set_keymap('n', '<Space>r', ':lua require("telescope.builtin").resume()<cr>',     { noremap = true })

  vim.api.nvim_create_user_command('H', function()
    require("telescope.builtin").help_tags()
  end, {})

  -- 参考: https://dev.classmethod.jp/articles/nvim_telescope
  require('telescope').setup({
    defaults = {
      mappings = {
        n = {
          ["<esc>"] = require('telescope.actions').close,
          ["<Space>q"] = require('telescope.actions').close,
        },
        i = {
          ["<esc>"] = require('telescope.actions').close,
          ["<C-a>"] = require('telescope.actions').send_to_qflist + require('telescope.actions').open_qflist,
          ["<C-q>"] = require('telescope.actions').send_selected_to_qflist + require('telescope.actions').open_qflist
        }
      },
    }
  })
  require('telescope').load_extension('fzy_native')
'''

# ファイル
[[plugins]]
repo = 'scrooloose/nerdtree'
lua_add = '''
  vim.g.NERDTreeShowHidden = 1
  vim.g.NERDTreeWinSize = 40
  vim.g.NERDTreeShowBookmarks = 1
  vim.g.NERDTreeMapMenu = 'm'
  vim.api.nvim_set_keymap('n', '<Space><Esc>', ':NERDTreeFind<CR>', { noremap = true, silent = true })
  vim.api.nvim_set_keymap('n', '<Space>`', ':NERDTreeFind<CR>', { noremap = true, silent = true })
  vim.cmd('cabbrev B Bookmark')
'''

[[plugins]] # nerd tree で nerd font
repo = 'ryanoasis/vim-devicons'
depends = ['scrooloose/nerdtree']

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]] # file_name:123 のように行数指定でファイルを開ける
repo = 'bogado/file-line'

# 補完系

[[multiple_plugins]]
plugins = [
  'Shougo/ddc.vim',
  'Shougo/ddc-ui-native',
  'Shougo/ddc-source-around',
  'shun/ddc-source-vim-lsp',
  'Shougo/ddc-matcher_head',
  'Shougo/ddc-sorter_rank',
  'Shougo/ddc-converter_remove_overlap',
]
hook_add = '''
  " ddc と ddc-source-vim-lsp のREADMEを参考に設定

  call ddc#custom#patch_global('ui', 'native')

  " 参考:
  " - https://note.com/dd_techblog/n/n97f2b6ca09d8
  call ddc#custom#patch_global('sources', ['vim-lsp', 'around'])
  call ddc#custom#patch_global('sourceOptions', {
  \ '_': {
  \   'matchers': ['matcher_head'],
  \   'sorters': ['sorter_rank'],
  \   'converters': ['converter_remove_overlap'],
  \   'ignoreCase': v:true,
  \ },
  \ 'around': {'mark': 'Around'},
  \ 'vim-lsp': {
  \   'mark': 'LSP',
  \   'matchers': ['matcher_head'],
  \   'forceCompletionPattern': '\.|:|->|"\w+/*'
  \ },
  \})

  call ddc#custom#patch_global('sourceParams', {
    \ 'around': {
    \   'maxSize': 500
    \ },
  \ })

  " Mappings

  " <TAB>: completion.
  inoremap <silent><expr> <TAB>
  \ pumvisible() ? '<C-n>' :
  \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
  \ '<TAB>' : ddc#map#manual_complete()

  " <S-TAB>: completion back.
  inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'

  " Use ddc.
  call ddc#enable()
'''

[[plugins]]
repo = 'github/copilot.vim'
# 初回起動時に :Copilot setup をする
# 認証情報は ~/.config/github-copilot/hosts.json に入る
hook_add = '''
  imap <C-f> <Plug>(copilot-next) " fallbackのf
  imap <silent><script><expr> <C-l> copilot#Accept("\<Right>")
  imap <silent><script><expr> <C-e> copilot#Accept("\<End>")
  imap <silent><script><expr> <Right> copilot#Accept("\<Right>")
  let g:copilot_no_tab_map = v:true
  nmap <C-g> <cmd>Copilot panel<CR>:setlocal nonumber<CR><C-w>L
'''

# LSP

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
# LspDocumentFormat, LspRename とかも便利そう
hook_add = '''
  let g:lsp_diagnostics_virtual_text_enabled = 0
  " エラーでも赤文字にしない
  let g:lsp_diagnostics_highlights_enabled = 0

  let g:lsp_diagnostics_signs_enabled = 0
  " let g:lsp_diagnostics_signs_error       = {'text': ''}
  " let g:lsp_diagnostics_signs_warning     = {'text': ''}
  " let g:lsp_diagnostics_signs_information = {'text': ''}
  " let g:lsp_diagnostics_signs_hint        = {'text': ''}

  " let g:lsp_diagnostics_float_cursor = 1
  " diagnosticsを即時に出す
  " let g:lsp_diagnostics_float_delay = 100

  nmap <Space><Space> <esc>:LspHover<CR>
  nmap <Space>]       <esc>:LspDefinition<CR>
  nmap <Space>[       <esc>:LspReference<CR>
  nmap <Space>d       <esc>:LspDocumentDiagnostics<CR>

  " autocmd! BufWritePre *.rb call execute('LspDocumentFormatSync')
  autocmd User lsp_setup call lsp#register_server({
    \ 'name': 'rubocop',
    \ 'cmd': {server_info->['rubocop', '--lsp']},
    \ 'allowlist': ['ruby'],
    \ })
'''

# TODO: vim-lsp-settings から脱却したい

# ここらへんのインストールが必要そう
# gem install rubocop-performance
# gem install rubocop-rspec
# gem install neovim
# g:ruby_host_prog
[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
  command! LspDebug let lsp_log_verbose=1 | let lsp_log_file = expand('~/Downloads/lsp.log') | call system("echo -n '' > ~/Downloads/lsp.log") | tabnew ~/Downloads/lsp.log
  let g:lsp_settings_filetype_ruby = ['steep', 'solargraph', 'rubocop']
'''

# 操作系

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]] # 選択箇所をyankで置き換え
repo = 'kana/vim-operator-replace'
lua_add = '''
  vim.api.nvim_set_keymap('n', 'R', '<Plug>(operator-replace)', {})
'''

[[plugins]] # kana/vim-operator-replaceが依存している
repo = 'kana/vim-operator-user'

[[plugins]] # CamelCase <=> snake_case
repo = 'tyru/operator-camelize.vim'
hook_add = '''
  vmap <Space>s <Plug>(operator-camelize-toggle)
'''

[[plugins]]
repo = 'scrooloose/nerdcommenter'
lua_add = '''
  vim.g.NERDSpaceDelims = 1
  vim.g.NERDDefaultAlign = 'left'
  vim.api.nvim_set_keymap('v', '<C-c>', '<Leader>c<Space>', {})
'''

# 表示系

[[plugins]]
repo = 'itchyny/lightline.vim'
# https://github.com/itchyny/lightline.vim/issues/293#issuecomment-373710096
hook_add = '''
  let g:lightline = {
        \ 'colorscheme': 'PaperColor',
        \ 'component_function': {
        \   'filename': 'LightlineFilename',
        \ }
        \ }
  function! LightlineFilename()
    let root = fnamemodify(get(b:, 'git_dir'), ':h')
    let path = expand('%:p')
    if path[:len(root)-1] ==# root
      return path[len(root)+1:]
    endif
    return expand('%')
  endfunction
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  " ctrl+eでのリサイズのサイズ
  let g:winresizer_vert_resize = 5
'''

[[plugins]] # カーソル下の単語を移動するたびにハイライトする
repo = 'osyo-manga/vim-brightest'
hook_add = '''
  let g:brightest#highlight = { "group" : "BrightestUnderline" }
  let g:brightest#pattern = '\k\+'
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
# これらを実行する
# :TSInstall ruby javascript typescript html css json yaml lua rust c cpp swift go haskell
# 確認
# :TSInstallInfo
hook_post_update = '''
  TSUpdate
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-context'
depends = ['nvim-treesitter']

[[plugins]] # 引数のハイライト
repo = 'm-demare/hlargs.nvim'
depends = ['nvim-treesitter']
lua_add = '''
  require('hlargs').setup {
    color = '#F0D0D0'
  }
'''

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
depends = ['nvim-treesitter']
lua_add = '''
  vim.opt.termguicolors = true
  vim.cmd [[highlight IndentBlanklineIndent1 guibg=#1f1f1f gui=nocombine]]
  vim.cmd [[highlight IndentBlanklineIndent2 guibg=#1a1a1a gui=nocombine]]

  require("indent_blankline").setup {
    char = "|",
  }
'''

[[plugins]] # 閉じ括弧補間
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
# 変な箇所で色がつくようなら以下を追加する
# autocmd FileType <desired_filetypes> EnableStripWhitespaceOnSave

# 検索・置換系

[[plugins]] # rubyやperl風正規表現(インクリメンタルサーチはできない)
repo = 'othree/eregex.vim'
# "/" will use :M/ to search. ",/" will use the original "/".
hook_add = '''
  let g:eregex_default_enable = 0
  nnoremap r/ :M/
'''

[[plugins]] # 検索結果数カウント
repo = 'henrik/vim-indexed-search'
hook_add = '''
  let g:indexed_search_dont_move = 1 " 検索時に1個下に動かないようになる
  let g:indexed_search_numbered_only = 1 " 検索カウントを簡素な表示に
  let g:indexed_search_shortmess = 1 " 検索カウントを簡素な表示に
'''

# mark系

[[plugins]]
repo = 'kshenoy/vim-signature'
lua_add = '''
  vim.g.SignatureMap = { ToggleMarkAtLine = "<Space>m", }
  vim.g.SignatureIncludeMarks = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  vim.api.nvim_set_keymap('n', '<Space>M', ':delmarks A-Z<CR>', { silent = true })
'''

[[plugins]] # コードに色付け(markとは別物) https://secret-garden.hatenablog.com/
repo = 't9md/vim-quickhl'
lua_add = '''
  local pattern = ([[
    binding.pry
    binding.irb
    NOTE:
    MEMO:
    <<<<<<<
    >>>>>>>
    =======
  ]]):gsub(" +", "")
     :gsub("\n", "\\|")
     :gsub("\\|$", "") -- 末尾についてしまう\|を削除
  vim.api.nvim_set_keymap('n', '<Space>h', '<Plug>(quickhl-manual-this)', { silent = true })
  vim.api.nvim_set_keymap('x', '<Space>h', '<Plug>(quickhl-manual-this)', { silent = true })
  vim.api.nvim_set_keymap('n', '<Space>H', '<Plug>(quickhl-manual-reset)', {silent = true })
  vim.g.quickhl_manual_enable_at_startup = 1
  vim.g.quickhl_manual_keywords = { { pattern = pattern, regexp = 1 }, }
'''

[[plugins]]
repo = 'RutaTang/quicknote.nvim'
depends = ['plenary.nvim']
lua_add = '''
  local quicknote = require("quicknote")
  quicknote.setup({})
  vim.cmd('autocmd BufEnter * lua require("quicknote").ShowNoteSigns()')

  function NewOrOpenNoteAtCurrentLine()
    if quicknote.OpenNoteAtCurrentLine() then
      print("note opened")
    else
      quicknote.NewNoteAtCurrentLine()
    end
  end
  vim.api.nvim_set_keymap("n", "<Space>n", "<cmd>:lua NewOrOpenNoteAtCurrentLine()<cr>",{})

  function DeleteNoteAtCurrentLineAndListNotesForCurrentBuffer()
    quicknote.DeleteNoteAtCurrentLine()
    quicknote.ListNotesForCurrentBuffer()
  end
  vim.api.nvim_set_keymap("n", "<Space>N", "<cmd>:lua DeleteNoteAtCurrentLineAndListNotesForCurrentBuffer()<cr>",{})
'''

# git系

[[plugins]] # gitコマンドをvimから使う
lazy = 1
on_cmd = ['Git', 'Ggrep', 'GBrowse']
repo = 'tpope/vim-fugitive'
hook_add = '''
  cabbrev g Ggrep
  cabbrev b GBrowse
  cabbrev l Git log --follow -p %
'''


[[plugins]] # vim-fugitiveのgithubサポート用
repo = 'tpope/vim-rhubarb'

[[plugins]] # gitのdiffを左端に表示
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_git_executable = substitute(system('which git'), '\n\+$', '', '')
'''

[[plugins]] # gitのviewer. :Agit, :AgitFile
lazy = 1
on_cmd = ['Agit', 'AgitFile']
repo = 'cohama/agit.vim'
hook_add = '''
  nmap <Space>a :AgitFile<CR>
'''

# コンフリクトをハイライト
# [x や ]x でコンフリクト間を移動
[[plugins]]
repo = 'rhysd/conflict-marker.vim'
hook_add = '''
  let g:conflict_marker_enable_mappings = 0
'''

# 言語系

## Ruby

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]] # heredocのsytax-highlight
repo = 'joker1007/vim-ruby-heredoc-syntax'
on_ft = 'ruby'

[[plugins]]
repo = 'pocke/rbs.vim'
on_ft = 'ruby'

[[plugins]]
repo = 'mrkn/vim-cruby' # set ft=c, set ft=cruby
# hook_add = '''
#   autocmd BufWinEnter,BufNewFile *.c,*.h,insns.def setlocal filetype=cruby
# '''

## JavaScript

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
hook_add = '''
  let g:vim_jsx_pretty_colorful_config = 1
  let g:vim_jsx_pretty_highlight_close_tag = 1
'''
on_ft = ['javascript', 'typescript', 'javascriptreact', 'typescriptreact']

## Crystal

[[plugins]]
repo = 'rhysd/vim-crystal'
on_ft = 'crystal'

## Slim

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

## Markdown

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
  " markdwonの折りたたみ無効化
  set nofoldenable
  let g:vim_markdown_folding_disabled = 1
  " markdown書くようの設定
  autocmd FileType markdown inoremap <Tab> <Esc>>>A
  autocmd FileType markdown inoremap <S-Tab> <Esc><<A
  let g:vim_markdown_conceal = 0
'''
on_ft = 'markdown'

## HTML

[[plugins]] # htmlのショートカット
repo = 'mattn/emmet-vim'
on_ft = 'html'
# 詳しくは https://raw.githubusercontent.com/mattn/emmet-vim/master/TUTORIAL
# Ctrl m , で展開
hook_add = '''
  let g:user_emmet_leader_key='<C-Z>'
  " let g:user_emmet_install_global = 0
  " auletocmd FileType html,css,typescriptreact EmmetInstall
'''
# (例)
# html:5  : html5のテンプレート
# ul>li*3 : リスト3つ
# div{}   : divタグの中身に{}を入れる
# visualで囲った後に使うと、タグでそれを囲める

## TOML

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

## CSV
[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = 'csv'

## PlantUML
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

## logファイル
[[plugins]]
repo = 'mtdl9/vim-log-highlighting'

# その他
[[plugins]]
repo = 'rizzatti/dash.vim'
hook_add = '''
  cabbrev d Dash
'''
