# 実行環境 (言語)
brew "mise"
brew "cmake"

# 実行環境 (言語以外)
brew "mysql"
brew "zsh"

# ターミナル
brew "tmux"

# エディタ
brew "neovim"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]

# git関連
brew "git"
brew "gh"
brew "git-delta"

# 便利ツール
brew "bat"
brew "jq"
brew "yq"
brew "pstree"
brew "rename"
brew "ripgrep"
brew "fzy"
brew "tree"
brew "wget"
brew "imagemagick"

# 便利ツール (Mac特有)
brew "fcanas/tap/mirror-displays"
brew "MonitorControl"
brew "trash"

# その他
brew "direnv"
brew "mas"

# caskツール
cask "docker"
cask "bettertouchtool"
cask "google-japanese-ime"
cask "clipy"
cask "karabiner-elements"
cask "alfred"
cask "font-noto-nerd-font"
cask "proxyman"

# 一般アプリ
cask "discord"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "sequel-ace"
cask "slack"
cask "skim"
cask "visual-studio-code"
cask "zoom"
cask "steam"

# mas
mas "QuickShade", id: 931571202
mas "RunCat", id: 1429033973
mas "Relax Melodies: Sleep Sounds", id: 467103113
mas "Kindle" id: 302584613

# tap
tap "homebrew/cask"
tap "homebrew/core"
tap "universal-ctags/universal-ctags"
tap "homebrew/cask-fonts"
