# インストール方法
# brew bundle --file ~/p/dotfiles/manual/Brewfile

# 実行環境 (言語)
brew "mise"
brew "cmake"

# 実行環境 (言語以外)
brew "mysql"
brew "zsh"

# ターミナル
brew "tmux"
brew "cormacrelf/tap/dark-notify" # ターミナルのテーマ変更を通知するツール (tmux-dark-notify で使用)
brew "herdr"

# エディタ
brew "neovim"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]

# git関連
brew "git"
brew "gh"
brew "git-delta"

# 便利ツール (開発)
brew "bat"
brew "jq"
brew "yq"
brew "pstree"
brew "rename"
brew "ripgrep"
brew "tree"
brew "wget"
brew "imagemagick"

# 便利ツール
brew "fcanas/tap/mirror-displays"
brew "MonitorControl"
brew "trash"

# その他
brew "direnv"
brew "mas"

# cask
cask "docker"
cask "google-japanese-ime"
cask "clipy"
cask "karabiner-elements"
cask "font-noto-nerd-font"
cask "qlmarkdown" # Quick LookでMarkdownをプレビューするツール

# 一般アプリ
cask "google-chrome"
cask "iterm2"
cask "sequel-ace"
cask "slack"
cask "skim"
cask "visual-studio-code"

# mas
mas "QuickShade", id: 931571202
mas "Kindle", id: 302584613
mas "BookFusion", id: 1141834096

# tap
tap "homebrew/cask"
tap "homebrew/core"
tap "universal-ctags/universal-ctags"
tap "homebrew/cask-fonts"
